### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by nongdancryptos** [ZkkuXyu/gradient-bot#1]
Please fix

Lỗi khi chạy node: Request failed with status code 404
Lỗi phản hồi: <!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1></body></html>
Lỗi: Request failed with status code 404
Lỗi phản hồi: <!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1></body></html>
Kết nối thất bại sau 3 lần thử
× bot tod không thể kết nối vào Gradient Network.

**Comment by ZkkuXyu** [comment]
Cảm ơn bạn đã phản hồi về mã tôi đã tạo và tôi đã sửa nó, vui lòng nhập đúng mã thông báo và email đã được đăng ký

**Comment by nongdancryptos** [comment]
> Cảm ơn bạn đã phản hồi về mã tôi đã tạo và tôi đã sửa nó, vui lòng nhập đúng mã thông báo và email đã được đăng ký

not working, please fix, thank sir
----------------------------------
Đang thử endpoint: /v1/connect
Endpoint /v1/connect không thành công: Request failed with status code 404
Đang thử endpoint: /api/connect
Endpoint /api/connect không thành công: Request failed with status code 404
Đang thử endpoint: /node/connect
Endpoint /node/connect không thành công: Request failed with status code 404
Đang thử endpoint: /connect
Endpoint /connect không thành công: Request failed with status code 404
Chi tiết lỗi: Không tìm được endpoint hợp lệ. Lỗi cuối cùng: Request failed with status code 404

**Comment by nongdancryptos** [comment]
token format is eyJh right?

**Comment by ZkkuXyu** [comment]
> token format is eyJh right?

yes token is eyjh

**Comment by nongdancryptos** [comment]
> > token format is eyJh right?
> 
> yes token is eyjh
it doesn't seem to work, the endpoint still fails and the Request failed with status code 404

**Comment by ZkkuXyu** [comment]
saya sudah memperbarui kode saya Terima kasih dan silakan di coba apabila ada kesalahan dalam kode saya sialakan di laporkan
