### ISSUE TITLE
Error with Token ID

### ISSUE THREAD

**Issue by jerrydao** [ZkkuXyu/gradient-bot#2]
![Screenshot 2024-12-06 211521](https://github.com/user-attachments/assets/270bb848-c1ac-4dfc-bbbb-7a526cca12d7)
No idea how to resolve this, Any help? I use the Token ID=eyJ...
I got the token ID wrong or I input it wrongly?

**Comment by ZkkuXyu** [comment]
This is the true
![Screenshot 2024-12-06 212318](https://github.com/user-attachments/assets/2d0e4257-687a-4dea-98d2-22b7198f07fd)

and this the wrong
![Screenshot 2024-12-06 212335](https://github.com/user-attachments/assets/c7686c89-4e95-474e-8790-b0dcfeab52b5)

**Comment by ZkkuXyu** [comment]
Thanks for the diligence and gratitude for the code I have created 
If the error still occurs, please contact me

**Comment by jerrydao** [comment]
The error still occurs, dont know why. can you guide me where to get the Token ID to be sure.
