### ISSUE TITLE
Error TOKEN ID

### ISSUE THREAD

**Issue by jerrydao** [ZkkuXyu/gradient-bot#3]
The error still remain the same. Dont know what is wrong.

**Comment by ZkkuXyu** [comment]
Wait i want to update

**Comment by ZkkuXyu** [comment]
Ok finish Klik F12 and go to network, klik statis, and copy authorization beare eyj.........
![Screenshot 2024-12-07 112635](https://github.com/user-attachments/assets/e63751ef-608c-4f3c-b3b4-58027fcc8e30)

**Comment by ZkkuXyu** [comment]
Have problem in my code asking to me more THX Sir.....
