### ISSUE TITLE
Error TOKEN_ID

### ISSUE THREAD

**Issue by jerrydao** [ZkkuXyu/gradient-bot#4]
I gave up. The error still remains... 
Error membaca file token.txt: Format baris tidak valid dalam token.txt

**Comment by ZkkuXyu** [comment]
Sepertinya saya tidak akan melanjutkan kode saya Dan saya akan belajar lagi untuk mengembangkan kode terima kasih sudah membantu saya menemukan kesalahan di kode saya Dan saya akan belajar lebih giat lagi agar saya bisa membuat kode yang lebih baik serta berhasil terima kasih teman ......
